### ISSUE TITLE
Impossible to resize Class/Interface/Structure box using Top Left handles

### ISSUE THREAD

**Issue by mrpetro** [gbaychev/NClass#1]
Top Left, Left and Top handles can't be used to resize the diagram element:
![resize class](https://user-images.githubusercontent.com/24554305/33680455-fc24769c-dac1-11e7-949e-0464a898158d.png)

User should have possibility to resize the element using all visible handles.

**Comment by gbaychev** [comment]
Hello,
agreed, I see no reason why the shapes should not be resized via all the handles.
Each shape has min height and width, that needs to be respected of course.

Do you want to try to fix that yourself and send me a pull request?

Apropos pull request, I saw that you fixed a minor issue yourself in your repo, do you want to send me a pull request about it?

**Comment by mrpetro** [comment]
Yes, I can pickup this issue and work on it.

About pull request, alright, I'll make pull request. I had a thought that I would make pull request after fixing more issues, but I'm happy to do this on every fix/ improvement.
BTW: Sorry for not creating an issue before fixing. I think it's better to keep history of issues so the fixes would be harder to duplicate. Will not make that mistake again.

**Comment by gbaychev** [comment]
No worries, mate, thank you for your help. 🍻 cheers.
