### ISSUE TITLE
No Undo Redo feature

### ISSUE THREAD

**Issue by KepekZul** [gbaychev/NClass#11]
I have difficulties to find undo and redo feature on windows. Do the said feature is not implemented?

**Comment by gbaychev** [comment]
Hello, 
sadly you are correct, undo/redo is currently missing, but it is on the TODO list.

Regards
Georgi

**Comment by KepekZul** [comment]
Interesting.
Is it possible for me to give a hand on this feature development? maybe it will not my top priority but I am interested in this project.

**Comment by KepekZul** [comment]
Interesting.
Is it possible for me to give a hand on this feature development? maybe it will not my top priority but I am interested in this project.

**Comment by gbaychev** [comment]
Sure, no problem. Currently I'm working on another feature and it's kinda difficult to find time for it, but after I'm done, I'm gonna sync with you once more.
