### ISSUE TITLE
It's impossible to generate diagrams from code or binaries

### ISSUE THREAD

**Issue by SamusAranX** [gbaychev/NClass#13]
Yeah, that.

There's only one "Open file" menu item and it only accepts NClass's own file format. How am I supposed to make NClass generate an UML diagram from my code?

**Comment by gbaychev** [comment]
Hello Peter,
you are supposed to use the plugin menu and import the assembly from there.

The reverse engineering of an .net assembly was implemented a long time ago
from another contributor as a plugin and given that there are java
diagrams, use-case diagrams are on the way and that you have the
theoretical option to have all the kind of diagrams, this the correct way
of implementation, which is not going to be changed.

So create a new project, a c# diagram and then via the plugin menu import
your assembly.

Regards

**Comment by gbaychev** [comment]
Since no feedback was heard, closing the issue
