### ISSUE TITLE
Predefined Styles are not shown in Options

### ISSUE THREAD

**Issue by pschimmel** [gbaychev/NClass#27]
I really like the improvement and bugfixes you have introduced to this project. 

I installed the latest MSI (v2.6.0). In the options it seems that the predefined styles are not shown anymore. I checked the installation folder and there are two .dst files in the styles folder, However those are not shown in the list.

**Comment by gbaychev** [comment]
Hello @pschimmel ,
thank you very much for your kind words and I'm glad that you are enjoying the program. :)

I've checked the code and I'm quite sure, that the default styles were never shown. I even have an older version, before I got involved in the project and the styles were not showing up there either.

Anyways, now this should be resolved, you could checkout the 2.6.1-pre.

Cheers 🍻
