### ISSUE TITLE
Can't read old NClass files

### ISSUE THREAD

**Issue by pschimmel** [gbaychev/NClass#28]
I don't know if this is intended, but I cannot open .ncp files created with the former version of NClass (I think it was 2.0.x, but I'm not sure as I uninstalled it). The error message says that "the save file is corrupt and could not be loaded".

Attached is a sample file.

[Example.zip](https://github.com/gbaychev/NClass/files/2945631/Example.zip)

**Comment by gbaychev** [comment]
Hi @pschimmel ,
TBH, I never thought that people using the older version are going to use this one, so I never gave much thought about backwards compatibility. It should be fixed now. Check v2.6.2-pre

BTW, thank you very much for reporting this, I suspect that some people simply download the project, see some broken stuff and never use it again.

Regards
