### ISSUE TITLE
Is this project coordinated with alexgracianoarj?

### ISSUE THREAD

**Issue by codebude** [gbaychev/NClass#31]
Hi,

I like to know, if this project is in anyway coordinated with https://github.com/alexgracianoarj/nclass ? I'm trying to find out, which one is more up-to-date/future-proof.

Kind regards,
Raffael

**Comment by gbaychev** [comment]
Hello Raffael,
thank you for inquiring. No, I was not aware at all that the other repository exists. For me, my repo is the more future proof. It seems that alex has pushed some stuff 5 months ago and either lost interest and/or has no time currently. I have some long term goals and plans for the project, but I need to take care of my kids, so my pace is very slow.

What do you have in mind, what do you want to implement?

Regards
Georgi

**Comment by gbaychev** [comment]
Well, thanks for stopping by, I guess.
