### ISSUE TITLE
Unable to open old projects after namespace feature(pre-release)

### ISSUE THREAD

**Issue by vishwas-trivedi** [gbaychev/NClass#32]
Hello,

This is about the problem that I found on pre-release installer :
https://github.com/gbaychev/NClass/issues/6#issuecomment-469403105

I just noticed following after using pre-release version v2.6.0-pre :

1). I'm unable to open old projects on the pre-release version. Following error is displayed :
"Error: The save file is corrupt and could not be loaded."

2). NClass icon in taskbar is not visible, white/empty icon is displayed.

As @gbaychev suggested I'm uploading a sample file that I had problem with.
[ClassDiagram.zip](https://github.com/gbaychev/NClass/files/3087464/ClassDiagram.zip)

Regards,
Vishwas

**Comment by gbaychev** [comment]
All of this should be fixed with release/v2.7.0
