### ISSUE TITLE
Error: The save file is corrupt and could not be loaded

### ISSUE THREAD

**Issue by WolfM00n** [gbaychev/NClass#41]
Project file gets corrupted at... some point. 
**NClass 2.7.0**
It is corrupted when migrated from original sourcefoge version, that is a file created with original version and then opened with version 2.7.0 modified and saved gets corrupted.
The same thing happens when a completely new file is created. After adding element (about 20 elements on a single class diagram) and saved, file cannot be opened even though it could be opened before.

**Comment by gbaychev** [comment]
Hi, thank you very much for reporting this.

Can you maybe attach some files, which got corrupted? I have some troubles reproducing the issue.

**Comment by gbaychev** [comment]
I know that you most likely won't respond, but still - do you have an event handler in one of your classes?

**Comment by gbaychev** [comment]
fa4611af67388dc will help in investigating the issue

**Comment by gbaychev** [comment]
Due to inactivity, I'm closing this.
