### ISSUE TITLE
Error: Could not read version data

### ISSUE THREAD

**Issue by Leemellaret** [gbaychev/NClass#42]
NClass 2.8.0 on Windows 10. Installed from "nclass.msi"
Error raise on opening nclass or if click Help->Check for Updates
![Screenshot_1](https://user-images.githubusercontent.com/38433380/91038004-763a5680-e623-11ea-86ab-1d16597e5b8b.png)

**Comment by Baltasarq** [comment]
Same here, NClass 2.8.0 downloaded from "nclass.zip".
Every time you run NClass you receive that dialog, as said.
Manjaro Linux with mono 6.10 installed.

**Comment by gbaychev** [comment]
Yes, it appears that some things did not get merged properly, should be with 2.8.1
