### ISSUE TITLE
Release 2.8.0 "nclass.zip" is wrongly built

### ISSUE THREAD

**Issue by Baltasarq** [gbaychev/NClass#43]
When you extract the file, instead of resulting in a folder structure with the "bin", "plugins", etc. directories, you have the files with their complete name:

- bin\NClass.exe
- Plugins\PDFExport.dll

And so on. It seems that the backslash is hard coded or something.
I was able to recreate the folder structure and removed the prefixes using the "rename" command present in linux (I can send it to you if it is of any help).

**Comment by gbaychev** [comment]
Yep, good catch. I use powershell to zip the binaries and it uses '\' as a separator. Weirdly enough ubuntu/debian unzip and archive manager have no problem, but oh well ¯\_(ツ)_/¯. Should be fine with 2.8.1
