### ISSUE TITLE
Zoom level label displaced in GUI

### ISSUE THREAD

**Issue by Baltasarq** [gbaychev/NClass#46]
I'm using Manjaro Linux with Mono 6.10.
This issue is probably related to Mono/Linux.
Very low importance.

As you can see below, the zoom label is misplaced, maybe somehow overflown.

![nclass](https://user-images.githubusercontent.com/201012/91289322-7efd6a80-e792-11ea-82d2-5f633e29957e.png)

**Comment by gbaychev** [comment]
Yes, this is mono specific. Not sure if I can do anything about it, but will check it out.

**Comment by Baltasarq** [comment]
I wonder if you really need to display that label. For me, is totally accessory.

**Comment by Baltasarq** [comment]
Okay, I know why this label is being misplaced. Yep it has to do with Mono and its implementation of WindowsForms.

But more importantly, it has to do with the way the GUI has been built. You've used the designer, and have hardcoded sizes and positions. This means that, if for some reason, any of the components changes it size, then the whole arrangement will fail, since there won't be room for any modification.

But of the whole toolbar, the problem with the label is that it probably changes its size because it uses a different font in Mono (while icons have all the same size always, of course).

I'd set a specific font and a specific size for that font so this won't happen. For example:

`toolZomValue.Font = new Font( FontFamily.GenericMonospace, 11 );`

I guess this can also be set in the designer.

**Comment by gbaychev** [comment]
Very good catch, I'm a bit curious, why the hell the font changes in mono, but whatever.

Yes, I can fix this, no problem, how's about that: do you want to create your fix and submit a PR? I can put you in the contributors list.

If you have no time/desire, it is also completely fine, just say so.

**Comment by Baltasarq** [comment]
> Yes, I can fix this, no problem, how's about that: do you want to create your fix and submit a PR? I can put you in the contributors list.

Thanks, I've created a pull request.

**Comment by Baltasarq** [comment]
Fixed now. Thanks!!
