### ISSUE TITLE
Classes that implement an interface don't have to adhere to the interface

### ISSUE THREAD

**Issue by JohnMarkHowell** [gbaychev/NClass#50]
When defining an interface and then define a class that implements that interface, there does not appear to be any restrictions to enforce that the class does, in fact, implement that interface.

It would also be helpful if I could right click on an interface entity and say 'create a class implementing this interface'.

Or am I missing some of the functionality?

**Comment by gbaychev** [comment]
Hello @JohnMarkHowell ,
thank you very much for reporting the issue. 

I'm not quite sure, that really enforcing it in the diagram is a good idea, although the code generation most definitely needs to be tweaked. 

As for your other question:

![image](https://user-images.githubusercontent.com/3358056/91965983-9055f200-ed11-11ea-817c-e4f0f9497711.png)


There is also a similar button in the EditMembers dialog, which you can use for now.
But I agree - a context menu entry should give a better visibility to this functonality.

**Comment by gbaychev** [comment]
I'm happy that you found what you were looking for and thank you very much for the kind words, John! :) When you are ready, your help will be welcome!
