### ISSUE TITLE
Copy past error

### ISSUE THREAD

**Issue by pikada-lab** [gbaychev/NClass#53]
![image](https://user-images.githubusercontent.com/31665156/94841325-86afcf00-0422-11eb-9e56-0b57abd02d7d.png)

Тут ошибка, она не несёт никакого эффекта, потому что инвертирование зависимостей нужно в данной программе только для PDF, но в дальнейшем вы можете сталкнуться при замене GDI.

---

There is an error here, it has no effect, because the inversion of dependencies is needed in this program only for PDF, but in the future you may stumble upon replacing GDI.

**Comment by gbaychev** [comment]
Very nicely spotted, you get a thumbs up from me, а спасибо and на здоровье.
