### ISSUE TITLE
Text garbled due to Source code encoding.

### ISSUE THREAD

**Issue by longlongago-k** [gbaychev/NClass#55]
Hi, "CSharpNamespace.cs" or some source codes are saved as ISO-8859-1, so Identifier text like stereotype have '<<' and '>>' characters are garbled at non-latin country.
Please save source code as UTF-8. ('<<' 0xAB will convert to U+226a)

![image](https://user-images.githubusercontent.com/46097651/97087302-1d5b5e80-1664-11eb-8a12-330ade23caea.png)

**Comment by gbaychev** [comment]
Nicely spotted, thank you very much!
