### ISSUE TITLE
.net assembly class diagram

### ISSUE THREAD

**Issue by ghost** [gbaychev/NClass#58]
Hello

I'm very new to the program. Is it possible to make class diagram from .net assembly? How to do this?

Jessica

**Comment by gbaychev** [comment]
Hello Jessica,
yes, it is possible, from the Main Menu->Plugins->Assembly Exporter. See the screenshot
![image](https://user-images.githubusercontent.com/3358056/159160504-d717ccef-a659-4cb3-8df2-9f7b4c40f652.png)
