### ISSUE TITLE
Can't delete selected element on Class diagram

### ISSUE THREAD

**Issue by rom320** [gbaychev/NClass#68]
I've used V2.04 for years.  Upgraded to 2.8.2.  Can't select class or connection and delete with delete key.  Cut button isn't enabled either.  I might be missing something obvious.

**Comment by rom320** [comment]
thanks very much for responding.  I'm on Windows10
I downgraded back to 2.0.4 yesterday after hitting the issue.  So today, I reinstalled 2.8.2 and can not recreate the problem.  I thought perhaps it was because it happened on a 2.0.4 file.  But everything now works there as well.

Thanks very much for providing this helpful tool.  much appreciated.

**Comment by gbaychev** [comment]
Oh, nice, I'm very glad that the problem resolved itself.

Thank you for your kind words. :)

Regards
