### ISSUE TITLE
FYI - I used NClass and reference it in my eBook/Sample App

### ISSUE THREAD

**Issue by AgileWithBlueprints** [gbaychev/NClass#70]
This isn't an issue/problem, but I wanted to notify you that I used NClass and reference it in my eBook/Sample Application. As I promote Agile w/ Blueprints, I hope it encourages more adoption of NClass.

www.agilewithblueprints.com 
https://github.com/AgileWithBlueprints/eRecipeBoxSampleApp

See
https://github.com/AgileWithBlueprints/eRecipeBoxSampleApp/tree/V24.1.3/eRecipeBoxSystem/eRecipeBox/Documentation 

eRecipeBoxArtifactsFinal, sections 3.1.1.2, 3.1.3.1.2.2, 3.1.3.2.4, 3.1.4.1.2, 3.2.4.1, 5.3.1

**Comment by gbaychev** [comment]
This is very nice of you, thank you very much. The book looks very nice.

There is a small thing I've noticed - you've linked to the original version on sourceforge (see section 5.3.1 NClass 2.8.2 – Freeware UML diagraming tool), was has not been maintained by the original author for a very long time (the last version there is 2.04, whereas in this repo is 2.82). It would be very cool, if you would link to this repo (https://github.com/gbaychev/NClass).

**Comment by AgileWithBlueprints** [comment]
Thanks.  I’ll change the link
