### ISSUE TITLE
Running on Mac/Linux?

### ISSUE THREAD

**Issue by fstonedahl** [gbaychev/NClass#71]
I love NClass and use this software in my classes when I teach students about object-oriented design. 

However, many of my students use Mac computers, and a few run Linux (as do I, on my laptop).

I know it should be possible to run this software on Mac & Linux using Mono, but... what's the easiest way of doing so?  Would the students have to build it from source?

Thanks!

**Comment by gbaychev** [comment]
Hello,

yes, NClass absolutely runs with mono under linux/mac. This is one of the reason I'm currently not considering to move the project to .net core. It is possible that some UI elements look a bit weird, but I haven't noticed big issues.

What you need to do is to grab [the zip from the latest release](https://github.com/gbaychev/NClass/releases/download/releases%2Fv2.8.2/nclass-v2.8.2.zip) and unzip it somewhere where it is convinient. 

Then you can call on your terminal:

`mono <the folder where you've extracted NClass>/bin/NClass.exe`

It is also possible that if you `chmod +x` the executable, you could skip the call to mono and start the exe directly, but currently I'm on a vacation and cannot verify it. I'm not that familiar with the current desktop enviroments for *nixes, but it is quite likely, that you could create a desktop shorcut encapsulating the mono call.

Thank you for your feedback, such messages could motivate to work on the project again.

I'm gonna close the issue now, if you need additional help, please simply reopen it.

Best regards
