### ISSUE TITLE
Unable to distinguish what type (C# or Java) of diagrams are on Projects view

### ISSUE THREAD

**Issue by mrpetro** [gbaychev/NClass#8]
Current project view doesn't inform user about types of diagrams being present in the project.

It should be possible distinguish the diagrams by their icon or prefix/suffix, i.e. [C#] SomeDiagram, [Java] Someother diagram  

![2018-01-05 22_45_59-sandbox_ - nclass](https://user-images.githubusercontent.com/24554305/34629935-5468992c-f26a-11e7-96b9-5832ecda1adb.png)

**Comment by gbaychev** [comment]
Is this really a use case? That you have a project, where you are mixing the languages?
Still some small hint may be in order though.

**Comment by mrpetro** [comment]
Yeah that's also something for the discussion. Should it be allowed to have project with diagrams for different languages? Sounds little bit without point. 
Wouldn't be better to create Projects oriented to specific language instead of diagrams?

![image](https://user-images.githubusercontent.com/24554305/34640691-a74e5cb6-f2f7-11e7-80cf-c08be80fc24c.png)

But if we will go with this plan, then  it will also mean that having option of destination language for code generation will also be pointless,

What do you think?

**Comment by gbaychev** [comment]
Yeah, actually it is possible that you have components in different languages. 
Also, Im currently implementing use case diagram functionality (at glacial pace) and will do sequence diagrams afterwards, which implies that you can have different type of diagrams in your project.

So, NClass stays as it is - multiple languages and diagram types per project and some kind if indicator for the different languages must be implemented. 

Either a prefix or the icons can be adjusted.

**Comment by mrpetro** [comment]
Alright, we staying with old functionality,
As for presenting type of diagram:
This is using prefixes:
![image](https://user-images.githubusercontent.com/24554305/34846347-28bd7416-f718-11e7-9530-c085057ab4ec.png)
Ant this is using my poor pixel art skills :)
![image](https://user-images.githubusercontent.com/24554305/34846482-a1951146-f718-11e7-9386-5fefa8fef01a.png)
How's that?

**Comment by gbaychev** [comment]
I like the adjusted icons. I think that you underestimate your pixel skills. 😄
